"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import fearing.header

class xbee(object):
    __slots__ = ["header", "rssi", "addr"]

    def __init__(self):
        self.header = fearing.header()
        self.rssi = 0
        self.addr = 0

    def encode(self):
        buf = BytesIO()
        buf.write(xbee._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.header._get_packed_fingerprint() == fearing.header._get_packed_fingerprint()
        self.header._encode_one(buf)
        buf.write(struct.pack(">qq", self.rssi, self.addr))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != xbee._get_packed_fingerprint():
            raise ValueError("Decode error")
        return xbee._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = xbee()
        self.header = fearing.header._decode_one(buf)
        self.rssi, self.addr = struct.unpack(">qq", buf.read(16))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if xbee in parents: return 0
        newparents = parents + [xbee]
        tmphash = (0x67ebd03fb3e553dc+ fearing.header._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if xbee._packed_fingerprint is None:
            xbee._packed_fingerprint = struct.pack(">Q", xbee._get_hash_recursive([]))
        return xbee._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

